const { zipSync, strToU8 } = require('fflate');
const sliced = `; generated by BambuStudio
G90
M83
; CHANGE_LAYER
; Z_HEIGHT: 0.2
G1 Z0.2 F1200
; FEATURE: Outer wall
G1 X20 Y0 E1
G1 X20 Y20 E1
G1 X0 Y20 E1
G1 X0 Y0 E1
G0 X5 Y5 F6000
; FEATURE: Sparse infill
G1 X15 Y15 E1
; CHANGE_LAYER
; Z_HEIGHT: 0.4
G0 Z0.4
; FEATURE: Outer wall
G1 X20 Y0 E1 F1200
G1 X20 Y20 E1
G1 X0 Y20 E1
G1 X0 Y0 E1
; CHANGE_LAYER
; Z_HEIGHT: 0.6
G0 Z0.6
; FEATURE: Top surface
G1 X20 Y0 E1
G1 X20 Y20 E1
G1 X0 Y20 E1
G1 X0 Y0 E1
`;
const model = `<?xml version="1.0" encoding="UTF-8"?><model unit="millimeter" xml:lang="en-US" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02"><resources><object id="1" type="model"><mesh><vertices><vertex x="0" y="0" z="0"/><vertex x="20" y="0" z="0"/><vertex x="0" y="20" z="0"/><vertex x="0" y="0" z="20"/></vertices><triangles><triangle v1="0" v2="2" v3="1"/><triangle v1="0" v2="1" v3="3"/><triangle v1="0" v2="3" v3="2"/><triangle v1="1" v2="2" v3="3"/></triangles></mesh></object></resources><build><item objectid="1"/></build></model>`;
function modelArchive() { return zipSync({
  '[Content_Types].xml': strToU8('<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="model" ContentType="application/vnd.ms-package.3dmanufacturing-3dmodel+xml"/></Types>'),
  '_rels/.rels':strToU8('<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Target="/3D/3dmodel.model" Id="rel0" Type="http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel"/></Relationships>'),
  '3D/3dmodel.model':strToU8(model)
}); }
const modelSettings='<config><object id="5"><metadata key="name" value="spool_case_body"/><part id="1"><metadata key="name" value="body_bottom"/></part><part id="2"><metadata key="name" value="body_text"/></part></object><plate><metadata key="plater_id" value="1"/><metadata key="gcode_file" value="Metadata/plate_1.gcode"/><model_instance><metadata key="object_id" value="5"/></model_instance></plate><plate><metadata key="plater_id" value="2"/><metadata key="gcode_file" value="Metadata/plate_2.gcode"/><model_instance><metadata key="object_id" value="5"/></model_instance></plate></config>';
function slicedArchive() { return zipSync({ 'Metadata/plate_1.gcode':strToU8(sliced), 'Metadata/plate_2.gcode':strToU8(sliced.replaceAll('Z_HEIGHT: 0.', 'Z_HEIGHT: 1.')), 'Metadata/model_settings.config':strToU8(modelSettings) }); }
module.exports={sliced,modelArchive,slicedArchive,modelSettings};
